#!/usr/bin/env python3
"""
Scene Viewer - Visualize generated 3D Modeler Pro JSON files
"""

import json
import sys
import argparse


def view_scene(filepath):
    """Display a formatted view of the scene."""
    with open(filepath, 'r') as f:
        data = json.load(f)
    
    print('=' * 70)
    print('🏠 3D MODELER PRO - SCENE VISUALIZATION')
    print('=' * 70)
    print()
    
    # Meta
    print('📊 META INFORMATION')
    meta = data['meta']
    print(f'   Version: {meta["version"]}')
    print(f'   Confidence: {meta["confidence"]:.0%}')
    print(f'   Generated by: {meta["generated_by"]}')
    print()
    
    # House
    print('🏗️  HOUSE STRUCTURE')
    house = data['house']
    print(f'   Type: {house["type"]}')
    print(f'   Shape: {house["footprint_shape"]}')
    print(f'   Total Area: {house["total_area_m2"]:.1f} m²')
    print(f'   Dimensions: {house["width_m"]:.2f}m × {house["depth_m"]:.2f}m')
    print(f'   Ceiling Height: {house["ceiling_height_m"]}m')
    print(f'   Floors: {house["floors"]}')
    print()
    
    # Rooms
    print(f'🚪 ROOMS ({len(data["rooms"])})')
    for i, room in enumerate(data['rooms'], 1):
        print(f'   {i}. {room["name"]} ({room["room_type"]})')
        print(f'      ID: {room["room_id"]}')
        print(f'      Area: {room["area_m2"]:.1f} m²')
        print(f'      Position: ({room["bounds"]["x"]:.2f}, {room["bounds"]["y"]:.2f})')
        print(f'      Size: {room["bounds"]["width"]:.2f}m × {room["bounds"]["depth"]:.2f}m')
        print(f'      Privacy: {room["privacy_level"]}')
        if room['adjacent_rooms']:
            print(f'      Adjacent: {", ".join(room["adjacent_rooms"])}')
        print()
    
    # Walls
    print(f'🧱 WALLS ({len(data["walls"])})')
    ext_walls = [w for w in data['walls'] if w['load_bearing']]
    int_walls = [w for w in data['walls'] if not w['load_bearing']]
    print(f'   Exterior: {len(ext_walls)} (load-bearing, {ext_walls[0]["thickness_m"]}m thick)')
    print(f'   Interior: {len(int_walls)} ({int_walls[0]["thickness_m"] if int_walls else 0}m thick)')
    print()
    
    # Openings
    print(f'🚪 OPENINGS ({len(data["openings"])})')
    doors = [o for o in data['openings'] if o['type'] == 'door']
    windows = [o for o in data['openings'] if o['type'] == 'window']
    print(f'   Doors: {len(doors)}')
    for door in doors:
        print(f'      - {door["opening_id"]}: {door["width_m"]}m × {door["height_m"]}m')
    print(f'   Windows: {len(windows)}')
    for window in windows:
        print(f'      - {window["opening_id"]}: {window["width_m"]}m × {window["height_m"]}m')
    print()
    
    # Furniture
    print(f'🪑 FURNITURE ({len(data["furniture"])})')
    for furn in data['furniture']:
        print(f'   - {furn["type"]} in {furn["room_id"]}')
        print(f'     Position: ({furn["position"][0]:.2f}, {furn["position"][1]:.2f})')
        print(f'     Preset: {furn["preset"]}')
    print()
    
    # Style
    print('🎨 STYLE')
    style = data['styles']
    print(f'   Theme: {style["theme"].upper()}')
    print(f'   Color Palette: {" ".join(style["color_palette"])}')
    print(f'   Material Bias: {style["material_bias"]}')
    print()
    
    # Materials
    print('📦 MATERIALS')
    for key, value in data['materials'].items():
        print(f'   {key}: {value}')
    print()
    
    # Constraints
    print('⚙️  CONSTRAINTS')
    constraints = data['constraints']
    print(f'   Budget: {constraints["budget_level"]}')
    print(f'   Region: {constraints["region_code"]}')
    print(f'   Accessibility: {"Wheelchair accessible" if constraints["accessibility"]["wheelchair"] else "Standard"}')
    print()
    
    # Exports
    print('📤 EXPORT CONFIGURATION')
    exports = data['exports']
    print(f'   Formats: {", ".join(exports["formats"])}')
    print(f'   Include Textures: {exports["include_textures"]}')
    print(f'   Include Furniture: {exports["include_furniture"]}')
    print(f'   Optimize Mesh: {exports["optimize_mesh"]}')
    print()
    
    print('=' * 70)


def main():
    parser = argparse.ArgumentParser(description='View 3D Modeler Pro scene files')
    parser.add_argument('file', help='JSON scene file to view')
    args = parser.parse_args()
    
    try:
        view_scene(args.file)
    except FileNotFoundError:
        print(f'Error: File "{args.file}" not found', file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f'Error: Invalid JSON - {e}', file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f'Error: {e}', file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
